[package]
name = "calcard"
version = "0.1.0"
edition = "2021"

[dependencies]
hashify = "0.2.6"
mail-builder = { version = "0.4", no-default-features = true }
mail-parser = "0.10.2"
rkyv = { version = "0.8", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["rkyv"]
rkyv = ["dep:rkyv"]
serde = ["dep:serde"]

[dev-dependencies]
serde = { version = "1.0.217", features = ["derive"] }
rkyv = { version = "0.8" }
