[package]
name = "calcard"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
chrono = "0.4.40"
chrono-tz = "0.10.3"
hashify = "0.2.6"
mail-builder = { version = "0.4", no-default-features = true }
mail-parser = "0.10.2"
rkyv = { version = "0.8", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["rkyv"]
rkyv = ["dep:rkyv"]
serde = ["dep:serde"]

[dev-dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
rkyv = { version = "0.8" }
serde_json = "1.0.140"
