/*
 * SPDX-FileCopyrightText: 2020 Stalwart Labs LLC <hello@stalw.art>
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 */

//! Stable numeric identifiers for IANA time zone names.
//!
//! [`Tz::as_id`](super::Tz::as_id) and [`Tz::from_id`](super::Tz::from_id)
//! expose these identifiers as a compact storage format, so the table is
//! committed verbatim rather than derived at build time: entries are never
//! reordered or removed, only appended. It was generated from the time zone
//! database bundled with `jiff`.
//!
//! A name maps to an identifier through a perfect hash and an identifier maps
//! back to a name by indexing, so neither direction searches.

/// Identifier of the `UTC` entry.
pub(super) const UTC_ID: u16 = 593;

static TZ_NAMES: [&str; 599] = [
    "Africa/Abidjan",
    "Africa/Accra",
    "Africa/Addis_Ababa",
    "Africa/Algiers",
    "Africa/Asmara",
    "Africa/Asmera",
    "Africa/Bamako",
    "Africa/Bangui",
    "Africa/Banjul",
    "Africa/Bissau",
    "Africa/Blantyre",
    "Africa/Brazzaville",
    "Africa/Bujumbura",
    "Africa/Cairo",
    "Africa/Casablanca",
    "Africa/Ceuta",
    "Africa/Conakry",
    "Africa/Dakar",
    "Africa/Dar_es_Salaam",
    "Africa/Djibouti",
    "Africa/Douala",
    "Africa/El_Aaiun",
    "Africa/Freetown",
    "Africa/Gaborone",
    "Africa/Harare",
    "Africa/Johannesburg",
    "Africa/Juba",
    "Africa/Kampala",
    "Africa/Khartoum",
    "Africa/Kigali",
    "Africa/Kinshasa",
    "Africa/Lagos",
    "Africa/Libreville",
    "Africa/Lome",
    "Africa/Luanda",
    "Africa/Lubumbashi",
    "Africa/Lusaka",
    "Africa/Malabo",
    "Africa/Maputo",
    "Africa/Maseru",
    "Africa/Mbabane",
    "Africa/Mogadishu",
    "Africa/Monrovia",
    "Africa/Nairobi",
    "Africa/Ndjamena",
    "Africa/Niamey",
    "Africa/Nouakchott",
    "Africa/Ouagadougou",
    "Africa/Porto-Novo",
    "Africa/Sao_Tome",
    "Africa/Timbuktu",
    "Africa/Tripoli",
    "Africa/Tunis",
    "Africa/Windhoek",
    "America/Adak",
    "America/Anchorage",
    "America/Anguilla",
    "America/Antigua",
    "America/Araguaina",
    "America/Argentina/Buenos_Aires",
    "America/Argentina/Catamarca",
    "America/Argentina/ComodRivadavia",
    "America/Argentina/Cordoba",
    "America/Argentina/Jujuy",
    "America/Argentina/La_Rioja",
    "America/Argentina/Mendoza",
    "America/Argentina/Rio_Gallegos",
    "America/Argentina/Salta",
    "America/Argentina/San_Juan",
    "America/Argentina/San_Luis",
    "America/Argentina/Tucuman",
    "America/Argentina/Ushuaia",
    "America/Aruba",
    "America/Asuncion",
    "America/Atikokan",
    "America/Atka",
    "America/Bahia",
    "America/Bahia_Banderas",
    "America/Barbados",
    "America/Belem",
    "America/Belize",
    "America/Blanc-Sablon",
    "America/Boa_Vista",
    "America/Bogota",
    "America/Boise",
    "America/Buenos_Aires",
    "America/Cambridge_Bay",
    "America/Campo_Grande",
    "America/Cancun",
    "America/Caracas",
    "America/Catamarca",
    "America/Cayenne",
    "America/Cayman",
    "America/Chicago",
    "America/Chihuahua",
    "America/Ciudad_Juarez",
    "America/Coral_Harbour",
    "America/Cordoba",
    "America/Costa_Rica",
    "America/Coyhaique",
    "America/Creston",
    "America/Cuiaba",
    "America/Curacao",
    "America/Danmarkshavn",
    "America/Dawson",
    "America/Dawson_Creek",
    "America/Denver",
    "America/Detroit",
    "America/Dominica",
    "America/Edmonton",
    "America/Eirunepe",
    "America/El_Salvador",
    "America/Ensenada",
    "America/Fort_Nelson",
    "America/Fort_Wayne",
    "America/Fortaleza",
    "America/Glace_Bay",
    "America/Godthab",
    "America/Goose_Bay",
    "America/Grand_Turk",
    "America/Grenada",
    "America/Guadeloupe",
    "America/Guatemala",
    "America/Guayaquil",
    "America/Guyana",
    "America/Halifax",
    "America/Havana",
    "America/Hermosillo",
    "America/Indiana/Indianapolis",
    "America/Indiana/Knox",
    "America/Indiana/Marengo",
    "America/Indiana/Petersburg",
    "America/Indiana/Tell_City",
    "America/Indiana/Vevay",
    "America/Indiana/Vincennes",
    "America/Indiana/Winamac",
    "America/Indianapolis",
    "America/Inuvik",
    "America/Iqaluit",
    "America/Jamaica",
    "America/Jujuy",
    "America/Juneau",
    "America/Kentucky/Louisville",
    "America/Kentucky/Monticello",
    "America/Knox_IN",
    "America/Kralendijk",
    "America/La_Paz",
    "America/Lima",
    "America/Los_Angeles",
    "America/Louisville",
    "America/Lower_Princes",
    "America/Maceio",
    "America/Managua",
    "America/Manaus",
    "America/Marigot",
    "America/Martinique",
    "America/Matamoros",
    "America/Mazatlan",
    "America/Mendoza",
    "America/Menominee",
    "America/Merida",
    "America/Metlakatla",
    "America/Mexico_City",
    "America/Miquelon",
    "America/Moncton",
    "America/Monterrey",
    "America/Montevideo",
    "America/Montreal",
    "America/Montserrat",
    "America/Nassau",
    "America/New_York",
    "America/Nipigon",
    "America/Nome",
    "America/Noronha",
    "America/North_Dakota/Beulah",
    "America/North_Dakota/Center",
    "America/North_Dakota/New_Salem",
    "America/Nuuk",
    "America/Ojinaga",
    "America/Panama",
    "America/Pangnirtung",
    "America/Paramaribo",
    "America/Phoenix",
    "America/Port-au-Prince",
    "America/Port_of_Spain",
    "America/Porto_Acre",
    "America/Porto_Velho",
    "America/Puerto_Rico",
    "America/Punta_Arenas",
    "America/Rainy_River",
    "America/Rankin_Inlet",
    "America/Recife",
    "America/Regina",
    "America/Resolute",
    "America/Rio_Branco",
    "America/Rosario",
    "America/Santa_Isabel",
    "America/Santarem",
    "America/Santiago",
    "America/Santo_Domingo",
    "America/Sao_Paulo",
    "America/Scoresbysund",
    "America/Shiprock",
    "America/Sitka",
    "America/St_Barthelemy",
    "America/St_Johns",
    "America/St_Kitts",
    "America/St_Lucia",
    "America/St_Thomas",
    "America/St_Vincent",
    "America/Swift_Current",
    "America/Tegucigalpa",
    "America/Thule",
    "America/Thunder_Bay",
    "America/Tijuana",
    "America/Toronto",
    "America/Tortola",
    "America/Vancouver",
    "America/Virgin",
    "America/Whitehorse",
    "America/Winnipeg",
    "America/Yakutat",
    "America/Yellowknife",
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/DumontDUrville",
    "Antarctica/Macquarie",
    "Antarctica/Mawson",
    "Antarctica/McMurdo",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/South_Pole",
    "Antarctica/Syowa",
    "Antarctica/Troll",
    "Antarctica/Vostok",
    "Arctic/Longyearbyen",
    "Asia/Aden",
    "Asia/Almaty",
    "Asia/Amman",
    "Asia/Anadyr",
    "Asia/Aqtau",
    "Asia/Aqtobe",
    "Asia/Ashgabat",
    "Asia/Ashkhabad",
    "Asia/Atyrau",
    "Asia/Baghdad",
    "Asia/Bahrain",
    "Asia/Baku",
    "Asia/Bangkok",
    "Asia/Barnaul",
    "Asia/Beirut",
    "Asia/Bishkek",
    "Asia/Brunei",
    "Asia/Calcutta",
    "Asia/Chita",
    "Asia/Choibalsan",
    "Asia/Chongqing",
    "Asia/Chungking",
    "Asia/Colombo",
    "Asia/Dacca",
    "Asia/Damascus",
    "Asia/Dhaka",
    "Asia/Dili",
    "Asia/Dubai",
    "Asia/Dushanbe",
    "Asia/Famagusta",
    "Asia/Gaza",
    "Asia/Harbin",
    "Asia/Hebron",
    "Asia/Ho_Chi_Minh",
    "Asia/Hong_Kong",
    "Asia/Hovd",
    "Asia/Irkutsk",
    "Asia/Istanbul",
    "Asia/Jakarta",
    "Asia/Jayapura",
    "Asia/Jerusalem",
    "Asia/Kabul",
    "Asia/Kamchatka",
    "Asia/Karachi",
    "Asia/Kashgar",
    "Asia/Kathmandu",
    "Asia/Katmandu",
    "Asia/Khandyga",
    "Asia/Kolkata",
    "Asia/Krasnoyarsk",
    "Asia/Kuala_Lumpur",
    "Asia/Kuching",
    "Asia/Kuwait",
    "Asia/Macao",
    "Asia/Macau",
    "Asia/Magadan",
    "Asia/Makassar",
    "Asia/Manila",
    "Asia/Muscat",
    "Asia/Nicosia",
    "Asia/Novokuznetsk",
    "Asia/Novosibirsk",
    "Asia/Omsk",
    "Asia/Oral",
    "Asia/Phnom_Penh",
    "Asia/Pontianak",
    "Asia/Pyongyang",
    "Asia/Qatar",
    "Asia/Qostanay",
    "Asia/Qyzylorda",
    "Asia/Rangoon",
    "Asia/Riyadh",
    "Asia/Saigon",
    "Asia/Sakhalin",
    "Asia/Samarkand",
    "Asia/Seoul",
    "Asia/Shanghai",
    "Asia/Singapore",
    "Asia/Srednekolymsk",
    "Asia/Taipei",
    "Asia/Tashkent",
    "Asia/Tbilisi",
    "Asia/Tehran",
    "Asia/Tel_Aviv",
    "Asia/Thimbu",
    "Asia/Thimphu",
    "Asia/Tokyo",
    "Asia/Tomsk",
    "Asia/Ujung_Pandang",
    "Asia/Ulaanbaatar",
    "Asia/Ulan_Bator",
    "Asia/Urumqi",
    "Asia/Ust-Nera",
    "Asia/Vientiane",
    "Asia/Vladivostok",
    "Asia/Yakutsk",
    "Asia/Yangon",
    "Asia/Yekaterinburg",
    "Asia/Yerevan",
    "Atlantic/Azores",
    "Atlantic/Bermuda",
    "Atlantic/Canary",
    "Atlantic/Cape_Verde",
    "Atlantic/Faeroe",
    "Atlantic/Faroe",
    "Atlantic/Jan_Mayen",
    "Atlantic/Madeira",
    "Atlantic/Reykjavik",
    "Atlantic/South_Georgia",
    "Atlantic/St_Helena",
    "Atlantic/Stanley",
    "Australia/ACT",
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Broken_Hill",
    "Australia/Canberra",
    "Australia/Currie",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Hobart",
    "Australia/LHI",
    "Australia/Lindeman",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/NSW",
    "Australia/North",
    "Australia/Perth",
    "Australia/Queensland",
    "Australia/South",
    "Australia/Sydney",
    "Australia/Tasmania",
    "Australia/Victoria",
    "Australia/West",
    "Australia/Yancowinna",
    "Brazil/Acre",
    "Brazil/DeNoronha",
    "Brazil/East",
    "Brazil/West",
    "CET",
    "CST6CDT",
    "Canada/Atlantic",
    "Canada/Central",
    "Canada/Eastern",
    "Canada/Mountain",
    "Canada/Newfoundland",
    "Canada/Pacific",
    "Canada/Saskatchewan",
    "Canada/Yukon",
    "Chile/Continental",
    "Chile/EasterIsland",
    "Cuba",
    "EET",
    "EST",
    "EST5EDT",
    "Egypt",
    "Eire",
    "Etc/GMT",
    "Etc/GMT+0",
    "Etc/GMT+1",
    "Etc/GMT+10",
    "Etc/GMT+11",
    "Etc/GMT+12",
    "Etc/GMT+2",
    "Etc/GMT+3",
    "Etc/GMT+4",
    "Etc/GMT+5",
    "Etc/GMT+6",
    "Etc/GMT+7",
    "Etc/GMT+8",
    "Etc/GMT+9",
    "Etc/GMT-0",
    "Etc/GMT-1",
    "Etc/GMT-10",
    "Etc/GMT-11",
    "Etc/GMT-12",
    "Etc/GMT-13",
    "Etc/GMT-14",
    "Etc/GMT-2",
    "Etc/GMT-3",
    "Etc/GMT-4",
    "Etc/GMT-5",
    "Etc/GMT-6",
    "Etc/GMT-7",
    "Etc/GMT-8",
    "Etc/GMT-9",
    "Etc/GMT0",
    "Etc/Greenwich",
    "Etc/UCT",
    "Etc/UTC",
    "Etc/Universal",
    "Etc/Zulu",
    "Europe/Amsterdam",
    "Europe/Andorra",
    "Europe/Astrakhan",
    "Europe/Athens",
    "Europe/Belfast",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Bucharest",
    "Europe/Budapest",
    "Europe/Busingen",
    "Europe/Chisinau",
    "Europe/Copenhagen",
    "Europe/Dublin",
    "Europe/Gibraltar",
    "Europe/Guernsey",
    "Europe/Helsinki",
    "Europe/Isle_of_Man",
    "Europe/Istanbul",
    "Europe/Jersey",
    "Europe/Kaliningrad",
    "Europe/Kiev",
    "Europe/Kirov",
    "Europe/Kyiv",
    "Europe/Lisbon",
    "Europe/Ljubljana",
    "Europe/London",
    "Europe/Luxembourg",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Mariehamn",
    "Europe/Minsk",
    "Europe/Monaco",
    "Europe/Moscow",
    "Europe/Nicosia",
    "Europe/Oslo",
    "Europe/Paris",
    "Europe/Podgorica",
    "Europe/Prague",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/Samara",
    "Europe/San_Marino",
    "Europe/Sarajevo",
    "Europe/Saratov",
    "Europe/Simferopol",
    "Europe/Skopje",
    "Europe/Sofia",
    "Europe/Stockholm",
    "Europe/Tallinn",
    "Europe/Tirane",
    "Europe/Tiraspol",
    "Europe/Ulyanovsk",
    "Europe/Uzhgorod",
    "Europe/Vaduz",
    "Europe/Vatican",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Volgograd",
    "Europe/Warsaw",
    "Europe/Zagreb",
    "Europe/Zaporozhye",
    "Europe/Zurich",
    "Factory",
    "GB",
    "GB-Eire",
    "GMT",
    "GMT+0",
    "GMT-0",
    "GMT0",
    "Greenwich",
    "HST",
    "Hongkong",
    "Iceland",
    "Indian/Antananarivo",
    "Indian/Chagos",
    "Indian/Christmas",
    "Indian/Cocos",
    "Indian/Comoro",
    "Indian/Kerguelen",
    "Indian/Mahe",
    "Indian/Maldives",
    "Indian/Mauritius",
    "Indian/Mayotte",
    "Indian/Reunion",
    "Iran",
    "Israel",
    "Jamaica",
    "Japan",
    "Kwajalein",
    "Libya",
    "MET",
    "MST",
    "MST7MDT",
    "Mexico/BajaNorte",
    "Mexico/BajaSur",
    "Mexico/General",
    "NZ",
    "NZ-CHAT",
    "Navajo",
    "PRC",
    "PST8PDT",
    "Pacific/Apia",
    "Pacific/Auckland",
    "Pacific/Bougainville",
    "Pacific/Chatham",
    "Pacific/Chuuk",
    "Pacific/Easter",
    "Pacific/Efate",
    "Pacific/Enderbury",
    "Pacific/Fakaofo",
    "Pacific/Fiji",
    "Pacific/Funafuti",
    "Pacific/Galapagos",
    "Pacific/Gambier",
    "Pacific/Guadalcanal",
    "Pacific/Guam",
    "Pacific/Honolulu",
    "Pacific/Johnston",
    "Pacific/Kanton",
    "Pacific/Kiritimati",
    "Pacific/Kosrae",
    "Pacific/Kwajalein",
    "Pacific/Majuro",
    "Pacific/Marquesas",
    "Pacific/Midway",
    "Pacific/Nauru",
    "Pacific/Niue",
    "Pacific/Norfolk",
    "Pacific/Noumea",
    "Pacific/Pago_Pago",
    "Pacific/Palau",
    "Pacific/Pitcairn",
    "Pacific/Pohnpei",
    "Pacific/Ponape",
    "Pacific/Port_Moresby",
    "Pacific/Rarotonga",
    "Pacific/Saipan",
    "Pacific/Samoa",
    "Pacific/Tahiti",
    "Pacific/Tarawa",
    "Pacific/Tongatapu",
    "Pacific/Truk",
    "Pacific/Wake",
    "Pacific/Wallis",
    "Pacific/Yap",
    "Poland",
    "Portugal",
    "ROC",
    "ROK",
    "Singapore",
    "Turkey",
    "UCT",
    "US/Alaska",
    "US/Aleutian",
    "US/Arizona",
    "US/Central",
    "US/East-Indiana",
    "US/Eastern",
    "US/Hawaii",
    "US/Indiana-Starke",
    "US/Michigan",
    "US/Mountain",
    "US/Pacific",
    "US/Samoa",
    "UTC",
    "Universal",
    "W-SU",
    "WET",
    "Zulu",
    "posixrules",
];

/// Returns the identifier assigned to an IANA time zone name.
pub(super) fn name_to_id(name: &str) -> Option<u16> {
    hashify::map!(name.as_bytes(), u16,
        "Africa/Abidjan" => 0,
        "Africa/Accra" => 1,
        "Africa/Addis_Ababa" => 2,
        "Africa/Algiers" => 3,
        "Africa/Asmara" => 4,
        "Africa/Asmera" => 5,
        "Africa/Bamako" => 6,
        "Africa/Bangui" => 7,
        "Africa/Banjul" => 8,
        "Africa/Bissau" => 9,
        "Africa/Blantyre" => 10,
        "Africa/Brazzaville" => 11,
        "Africa/Bujumbura" => 12,
        "Africa/Cairo" => 13,
        "Africa/Casablanca" => 14,
        "Africa/Ceuta" => 15,
        "Africa/Conakry" => 16,
        "Africa/Dakar" => 17,
        "Africa/Dar_es_Salaam" => 18,
        "Africa/Djibouti" => 19,
        "Africa/Douala" => 20,
        "Africa/El_Aaiun" => 21,
        "Africa/Freetown" => 22,
        "Africa/Gaborone" => 23,
        "Africa/Harare" => 24,
        "Africa/Johannesburg" => 25,
        "Africa/Juba" => 26,
        "Africa/Kampala" => 27,
        "Africa/Khartoum" => 28,
        "Africa/Kigali" => 29,
        "Africa/Kinshasa" => 30,
        "Africa/Lagos" => 31,
        "Africa/Libreville" => 32,
        "Africa/Lome" => 33,
        "Africa/Luanda" => 34,
        "Africa/Lubumbashi" => 35,
        "Africa/Lusaka" => 36,
        "Africa/Malabo" => 37,
        "Africa/Maputo" => 38,
        "Africa/Maseru" => 39,
        "Africa/Mbabane" => 40,
        "Africa/Mogadishu" => 41,
        "Africa/Monrovia" => 42,
        "Africa/Nairobi" => 43,
        "Africa/Ndjamena" => 44,
        "Africa/Niamey" => 45,
        "Africa/Nouakchott" => 46,
        "Africa/Ouagadougou" => 47,
        "Africa/Porto-Novo" => 48,
        "Africa/Sao_Tome" => 49,
        "Africa/Timbuktu" => 50,
        "Africa/Tripoli" => 51,
        "Africa/Tunis" => 52,
        "Africa/Windhoek" => 53,
        "America/Adak" => 54,
        "America/Anchorage" => 55,
        "America/Anguilla" => 56,
        "America/Antigua" => 57,
        "America/Araguaina" => 58,
        "America/Argentina/Buenos_Aires" => 59,
        "America/Argentina/Catamarca" => 60,
        "America/Argentina/ComodRivadavia" => 61,
        "America/Argentina/Cordoba" => 62,
        "America/Argentina/Jujuy" => 63,
        "America/Argentina/La_Rioja" => 64,
        "America/Argentina/Mendoza" => 65,
        "America/Argentina/Rio_Gallegos" => 66,
        "America/Argentina/Salta" => 67,
        "America/Argentina/San_Juan" => 68,
        "America/Argentina/San_Luis" => 69,
        "America/Argentina/Tucuman" => 70,
        "America/Argentina/Ushuaia" => 71,
        "America/Aruba" => 72,
        "America/Asuncion" => 73,
        "America/Atikokan" => 74,
        "America/Atka" => 75,
        "America/Bahia" => 76,
        "America/Bahia_Banderas" => 77,
        "America/Barbados" => 78,
        "America/Belem" => 79,
        "America/Belize" => 80,
        "America/Blanc-Sablon" => 81,
        "America/Boa_Vista" => 82,
        "America/Bogota" => 83,
        "America/Boise" => 84,
        "America/Buenos_Aires" => 85,
        "America/Cambridge_Bay" => 86,
        "America/Campo_Grande" => 87,
        "America/Cancun" => 88,
        "America/Caracas" => 89,
        "America/Catamarca" => 90,
        "America/Cayenne" => 91,
        "America/Cayman" => 92,
        "America/Chicago" => 93,
        "America/Chihuahua" => 94,
        "America/Ciudad_Juarez" => 95,
        "America/Coral_Harbour" => 96,
        "America/Cordoba" => 97,
        "America/Costa_Rica" => 98,
        "America/Coyhaique" => 99,
        "America/Creston" => 100,
        "America/Cuiaba" => 101,
        "America/Curacao" => 102,
        "America/Danmarkshavn" => 103,
        "America/Dawson" => 104,
        "America/Dawson_Creek" => 105,
        "America/Denver" => 106,
        "America/Detroit" => 107,
        "America/Dominica" => 108,
        "America/Edmonton" => 109,
        "America/Eirunepe" => 110,
        "America/El_Salvador" => 111,
        "America/Ensenada" => 112,
        "America/Fort_Nelson" => 113,
        "America/Fort_Wayne" => 114,
        "America/Fortaleza" => 115,
        "America/Glace_Bay" => 116,
        "America/Godthab" => 117,
        "America/Goose_Bay" => 118,
        "America/Grand_Turk" => 119,
        "America/Grenada" => 120,
        "America/Guadeloupe" => 121,
        "America/Guatemala" => 122,
        "America/Guayaquil" => 123,
        "America/Guyana" => 124,
        "America/Halifax" => 125,
        "America/Havana" => 126,
        "America/Hermosillo" => 127,
        "America/Indiana/Indianapolis" => 128,
        "America/Indiana/Knox" => 129,
        "America/Indiana/Marengo" => 130,
        "America/Indiana/Petersburg" => 131,
        "America/Indiana/Tell_City" => 132,
        "America/Indiana/Vevay" => 133,
        "America/Indiana/Vincennes" => 134,
        "America/Indiana/Winamac" => 135,
        "America/Indianapolis" => 136,
        "America/Inuvik" => 137,
        "America/Iqaluit" => 138,
        "America/Jamaica" => 139,
        "America/Jujuy" => 140,
        "America/Juneau" => 141,
        "America/Kentucky/Louisville" => 142,
        "America/Kentucky/Monticello" => 143,
        "America/Knox_IN" => 144,
        "America/Kralendijk" => 145,
        "America/La_Paz" => 146,
        "America/Lima" => 147,
        "America/Los_Angeles" => 148,
        "America/Louisville" => 149,
        "America/Lower_Princes" => 150,
        "America/Maceio" => 151,
        "America/Managua" => 152,
        "America/Manaus" => 153,
        "America/Marigot" => 154,
        "America/Martinique" => 155,
        "America/Matamoros" => 156,
        "America/Mazatlan" => 157,
        "America/Mendoza" => 158,
        "America/Menominee" => 159,
        "America/Merida" => 160,
        "America/Metlakatla" => 161,
        "America/Mexico_City" => 162,
        "America/Miquelon" => 163,
        "America/Moncton" => 164,
        "America/Monterrey" => 165,
        "America/Montevideo" => 166,
        "America/Montreal" => 167,
        "America/Montserrat" => 168,
        "America/Nassau" => 169,
        "America/New_York" => 170,
        "America/Nipigon" => 171,
        "America/Nome" => 172,
        "America/Noronha" => 173,
        "America/North_Dakota/Beulah" => 174,
        "America/North_Dakota/Center" => 175,
        "America/North_Dakota/New_Salem" => 176,
        "America/Nuuk" => 177,
        "America/Ojinaga" => 178,
        "America/Panama" => 179,
        "America/Pangnirtung" => 180,
        "America/Paramaribo" => 181,
        "America/Phoenix" => 182,
        "America/Port-au-Prince" => 183,
        "America/Port_of_Spain" => 184,
        "America/Porto_Acre" => 185,
        "America/Porto_Velho" => 186,
        "America/Puerto_Rico" => 187,
        "America/Punta_Arenas" => 188,
        "America/Rainy_River" => 189,
        "America/Rankin_Inlet" => 190,
        "America/Recife" => 191,
        "America/Regina" => 192,
        "America/Resolute" => 193,
        "America/Rio_Branco" => 194,
        "America/Rosario" => 195,
        "America/Santa_Isabel" => 196,
        "America/Santarem" => 197,
        "America/Santiago" => 198,
        "America/Santo_Domingo" => 199,
        "America/Sao_Paulo" => 200,
        "America/Scoresbysund" => 201,
        "America/Shiprock" => 202,
        "America/Sitka" => 203,
        "America/St_Barthelemy" => 204,
        "America/St_Johns" => 205,
        "America/St_Kitts" => 206,
        "America/St_Lucia" => 207,
        "America/St_Thomas" => 208,
        "America/St_Vincent" => 209,
        "America/Swift_Current" => 210,
        "America/Tegucigalpa" => 211,
        "America/Thule" => 212,
        "America/Thunder_Bay" => 213,
        "America/Tijuana" => 214,
        "America/Toronto" => 215,
        "America/Tortola" => 216,
        "America/Vancouver" => 217,
        "America/Virgin" => 218,
        "America/Whitehorse" => 219,
        "America/Winnipeg" => 220,
        "America/Yakutat" => 221,
        "America/Yellowknife" => 222,
        "Antarctica/Casey" => 223,
        "Antarctica/Davis" => 224,
        "Antarctica/DumontDUrville" => 225,
        "Antarctica/Macquarie" => 226,
        "Antarctica/Mawson" => 227,
        "Antarctica/McMurdo" => 228,
        "Antarctica/Palmer" => 229,
        "Antarctica/Rothera" => 230,
        "Antarctica/South_Pole" => 231,
        "Antarctica/Syowa" => 232,
        "Antarctica/Troll" => 233,
        "Antarctica/Vostok" => 234,
        "Arctic/Longyearbyen" => 235,
        "Asia/Aden" => 236,
        "Asia/Almaty" => 237,
        "Asia/Amman" => 238,
        "Asia/Anadyr" => 239,
        "Asia/Aqtau" => 240,
        "Asia/Aqtobe" => 241,
        "Asia/Ashgabat" => 242,
        "Asia/Ashkhabad" => 243,
        "Asia/Atyrau" => 244,
        "Asia/Baghdad" => 245,
        "Asia/Bahrain" => 246,
        "Asia/Baku" => 247,
        "Asia/Bangkok" => 248,
        "Asia/Barnaul" => 249,
        "Asia/Beirut" => 250,
        "Asia/Bishkek" => 251,
        "Asia/Brunei" => 252,
        "Asia/Calcutta" => 253,
        "Asia/Chita" => 254,
        "Asia/Choibalsan" => 255,
        "Asia/Chongqing" => 256,
        "Asia/Chungking" => 257,
        "Asia/Colombo" => 258,
        "Asia/Dacca" => 259,
        "Asia/Damascus" => 260,
        "Asia/Dhaka" => 261,
        "Asia/Dili" => 262,
        "Asia/Dubai" => 263,
        "Asia/Dushanbe" => 264,
        "Asia/Famagusta" => 265,
        "Asia/Gaza" => 266,
        "Asia/Harbin" => 267,
        "Asia/Hebron" => 268,
        "Asia/Ho_Chi_Minh" => 269,
        "Asia/Hong_Kong" => 270,
        "Asia/Hovd" => 271,
        "Asia/Irkutsk" => 272,
        "Asia/Istanbul" => 273,
        "Asia/Jakarta" => 274,
        "Asia/Jayapura" => 275,
        "Asia/Jerusalem" => 276,
        "Asia/Kabul" => 277,
        "Asia/Kamchatka" => 278,
        "Asia/Karachi" => 279,
        "Asia/Kashgar" => 280,
        "Asia/Kathmandu" => 281,
        "Asia/Katmandu" => 282,
        "Asia/Khandyga" => 283,
        "Asia/Kolkata" => 284,
        "Asia/Krasnoyarsk" => 285,
        "Asia/Kuala_Lumpur" => 286,
        "Asia/Kuching" => 287,
        "Asia/Kuwait" => 288,
        "Asia/Macao" => 289,
        "Asia/Macau" => 290,
        "Asia/Magadan" => 291,
        "Asia/Makassar" => 292,
        "Asia/Manila" => 293,
        "Asia/Muscat" => 294,
        "Asia/Nicosia" => 295,
        "Asia/Novokuznetsk" => 296,
        "Asia/Novosibirsk" => 297,
        "Asia/Omsk" => 298,
        "Asia/Oral" => 299,
        "Asia/Phnom_Penh" => 300,
        "Asia/Pontianak" => 301,
        "Asia/Pyongyang" => 302,
        "Asia/Qatar" => 303,
        "Asia/Qostanay" => 304,
        "Asia/Qyzylorda" => 305,
        "Asia/Rangoon" => 306,
        "Asia/Riyadh" => 307,
        "Asia/Saigon" => 308,
        "Asia/Sakhalin" => 309,
        "Asia/Samarkand" => 310,
        "Asia/Seoul" => 311,
        "Asia/Shanghai" => 312,
        "Asia/Singapore" => 313,
        "Asia/Srednekolymsk" => 314,
        "Asia/Taipei" => 315,
        "Asia/Tashkent" => 316,
        "Asia/Tbilisi" => 317,
        "Asia/Tehran" => 318,
        "Asia/Tel_Aviv" => 319,
        "Asia/Thimbu" => 320,
        "Asia/Thimphu" => 321,
        "Asia/Tokyo" => 322,
        "Asia/Tomsk" => 323,
        "Asia/Ujung_Pandang" => 324,
        "Asia/Ulaanbaatar" => 325,
        "Asia/Ulan_Bator" => 326,
        "Asia/Urumqi" => 327,
        "Asia/Ust-Nera" => 328,
        "Asia/Vientiane" => 329,
        "Asia/Vladivostok" => 330,
        "Asia/Yakutsk" => 331,
        "Asia/Yangon" => 332,
        "Asia/Yekaterinburg" => 333,
        "Asia/Yerevan" => 334,
        "Atlantic/Azores" => 335,
        "Atlantic/Bermuda" => 336,
        "Atlantic/Canary" => 337,
        "Atlantic/Cape_Verde" => 338,
        "Atlantic/Faeroe" => 339,
        "Atlantic/Faroe" => 340,
        "Atlantic/Jan_Mayen" => 341,
        "Atlantic/Madeira" => 342,
        "Atlantic/Reykjavik" => 343,
        "Atlantic/South_Georgia" => 344,
        "Atlantic/St_Helena" => 345,
        "Atlantic/Stanley" => 346,
        "Australia/ACT" => 347,
        "Australia/Adelaide" => 348,
        "Australia/Brisbane" => 349,
        "Australia/Broken_Hill" => 350,
        "Australia/Canberra" => 351,
        "Australia/Currie" => 352,
        "Australia/Darwin" => 353,
        "Australia/Eucla" => 354,
        "Australia/Hobart" => 355,
        "Australia/LHI" => 356,
        "Australia/Lindeman" => 357,
        "Australia/Lord_Howe" => 358,
        "Australia/Melbourne" => 359,
        "Australia/NSW" => 360,
        "Australia/North" => 361,
        "Australia/Perth" => 362,
        "Australia/Queensland" => 363,
        "Australia/South" => 364,
        "Australia/Sydney" => 365,
        "Australia/Tasmania" => 366,
        "Australia/Victoria" => 367,
        "Australia/West" => 368,
        "Australia/Yancowinna" => 369,
        "Brazil/Acre" => 370,
        "Brazil/DeNoronha" => 371,
        "Brazil/East" => 372,
        "Brazil/West" => 373,
        "CET" => 374,
        "CST6CDT" => 375,
        "Canada/Atlantic" => 376,
        "Canada/Central" => 377,
        "Canada/Eastern" => 378,
        "Canada/Mountain" => 379,
        "Canada/Newfoundland" => 380,
        "Canada/Pacific" => 381,
        "Canada/Saskatchewan" => 382,
        "Canada/Yukon" => 383,
        "Chile/Continental" => 384,
        "Chile/EasterIsland" => 385,
        "Cuba" => 386,
        "EET" => 387,
        "EST" => 388,
        "EST5EDT" => 389,
        "Egypt" => 390,
        "Eire" => 391,
        "Etc/GMT" => 392,
        "Etc/GMT+0" => 393,
        "Etc/GMT+1" => 394,
        "Etc/GMT+10" => 395,
        "Etc/GMT+11" => 396,
        "Etc/GMT+12" => 397,
        "Etc/GMT+2" => 398,
        "Etc/GMT+3" => 399,
        "Etc/GMT+4" => 400,
        "Etc/GMT+5" => 401,
        "Etc/GMT+6" => 402,
        "Etc/GMT+7" => 403,
        "Etc/GMT+8" => 404,
        "Etc/GMT+9" => 405,
        "Etc/GMT-0" => 406,
        "Etc/GMT-1" => 407,
        "Etc/GMT-10" => 408,
        "Etc/GMT-11" => 409,
        "Etc/GMT-12" => 410,
        "Etc/GMT-13" => 411,
        "Etc/GMT-14" => 412,
        "Etc/GMT-2" => 413,
        "Etc/GMT-3" => 414,
        "Etc/GMT-4" => 415,
        "Etc/GMT-5" => 416,
        "Etc/GMT-6" => 417,
        "Etc/GMT-7" => 418,
        "Etc/GMT-8" => 419,
        "Etc/GMT-9" => 420,
        "Etc/GMT0" => 421,
        "Etc/Greenwich" => 422,
        "Etc/UCT" => 423,
        "Etc/UTC" => 424,
        "Etc/Universal" => 425,
        "Etc/Zulu" => 426,
        "Europe/Amsterdam" => 427,
        "Europe/Andorra" => 428,
        "Europe/Astrakhan" => 429,
        "Europe/Athens" => 430,
        "Europe/Belfast" => 431,
        "Europe/Belgrade" => 432,
        "Europe/Berlin" => 433,
        "Europe/Bratislava" => 434,
        "Europe/Brussels" => 435,
        "Europe/Bucharest" => 436,
        "Europe/Budapest" => 437,
        "Europe/Busingen" => 438,
        "Europe/Chisinau" => 439,
        "Europe/Copenhagen" => 440,
        "Europe/Dublin" => 441,
        "Europe/Gibraltar" => 442,
        "Europe/Guernsey" => 443,
        "Europe/Helsinki" => 444,
        "Europe/Isle_of_Man" => 445,
        "Europe/Istanbul" => 446,
        "Europe/Jersey" => 447,
        "Europe/Kaliningrad" => 448,
        "Europe/Kiev" => 449,
        "Europe/Kirov" => 450,
        "Europe/Kyiv" => 451,
        "Europe/Lisbon" => 452,
        "Europe/Ljubljana" => 453,
        "Europe/London" => 454,
        "Europe/Luxembourg" => 455,
        "Europe/Madrid" => 456,
        "Europe/Malta" => 457,
        "Europe/Mariehamn" => 458,
        "Europe/Minsk" => 459,
        "Europe/Monaco" => 460,
        "Europe/Moscow" => 461,
        "Europe/Nicosia" => 462,
        "Europe/Oslo" => 463,
        "Europe/Paris" => 464,
        "Europe/Podgorica" => 465,
        "Europe/Prague" => 466,
        "Europe/Riga" => 467,
        "Europe/Rome" => 468,
        "Europe/Samara" => 469,
        "Europe/San_Marino" => 470,
        "Europe/Sarajevo" => 471,
        "Europe/Saratov" => 472,
        "Europe/Simferopol" => 473,
        "Europe/Skopje" => 474,
        "Europe/Sofia" => 475,
        "Europe/Stockholm" => 476,
        "Europe/Tallinn" => 477,
        "Europe/Tirane" => 478,
        "Europe/Tiraspol" => 479,
        "Europe/Ulyanovsk" => 480,
        "Europe/Uzhgorod" => 481,
        "Europe/Vaduz" => 482,
        "Europe/Vatican" => 483,
        "Europe/Vienna" => 484,
        "Europe/Vilnius" => 485,
        "Europe/Volgograd" => 486,
        "Europe/Warsaw" => 487,
        "Europe/Zagreb" => 488,
        "Europe/Zaporozhye" => 489,
        "Europe/Zurich" => 490,
        "Factory" => 491,
        "GB" => 492,
        "GB-Eire" => 493,
        "GMT" => 494,
        "GMT+0" => 495,
        "GMT-0" => 496,
        "GMT0" => 497,
        "Greenwich" => 498,
        "HST" => 499,
        "Hongkong" => 500,
        "Iceland" => 501,
        "Indian/Antananarivo" => 502,
        "Indian/Chagos" => 503,
        "Indian/Christmas" => 504,
        "Indian/Cocos" => 505,
        "Indian/Comoro" => 506,
        "Indian/Kerguelen" => 507,
        "Indian/Mahe" => 508,
        "Indian/Maldives" => 509,
        "Indian/Mauritius" => 510,
        "Indian/Mayotte" => 511,
        "Indian/Reunion" => 512,
        "Iran" => 513,
        "Israel" => 514,
        "Jamaica" => 515,
        "Japan" => 516,
        "Kwajalein" => 517,
        "Libya" => 518,
        "MET" => 519,
        "MST" => 520,
        "MST7MDT" => 521,
        "Mexico/BajaNorte" => 522,
        "Mexico/BajaSur" => 523,
        "Mexico/General" => 524,
        "NZ" => 525,
        "NZ-CHAT" => 526,
        "Navajo" => 527,
        "PRC" => 528,
        "PST8PDT" => 529,
        "Pacific/Apia" => 530,
        "Pacific/Auckland" => 531,
        "Pacific/Bougainville" => 532,
        "Pacific/Chatham" => 533,
        "Pacific/Chuuk" => 534,
        "Pacific/Easter" => 535,
        "Pacific/Efate" => 536,
        "Pacific/Enderbury" => 537,
        "Pacific/Fakaofo" => 538,
        "Pacific/Fiji" => 539,
        "Pacific/Funafuti" => 540,
        "Pacific/Galapagos" => 541,
        "Pacific/Gambier" => 542,
        "Pacific/Guadalcanal" => 543,
        "Pacific/Guam" => 544,
        "Pacific/Honolulu" => 545,
        "Pacific/Johnston" => 546,
        "Pacific/Kanton" => 547,
        "Pacific/Kiritimati" => 548,
        "Pacific/Kosrae" => 549,
        "Pacific/Kwajalein" => 550,
        "Pacific/Majuro" => 551,
        "Pacific/Marquesas" => 552,
        "Pacific/Midway" => 553,
        "Pacific/Nauru" => 554,
        "Pacific/Niue" => 555,
        "Pacific/Norfolk" => 556,
        "Pacific/Noumea" => 557,
        "Pacific/Pago_Pago" => 558,
        "Pacific/Palau" => 559,
        "Pacific/Pitcairn" => 560,
        "Pacific/Pohnpei" => 561,
        "Pacific/Ponape" => 562,
        "Pacific/Port_Moresby" => 563,
        "Pacific/Rarotonga" => 564,
        "Pacific/Saipan" => 565,
        "Pacific/Samoa" => 566,
        "Pacific/Tahiti" => 567,
        "Pacific/Tarawa" => 568,
        "Pacific/Tongatapu" => 569,
        "Pacific/Truk" => 570,
        "Pacific/Wake" => 571,
        "Pacific/Wallis" => 572,
        "Pacific/Yap" => 573,
        "Poland" => 574,
        "Portugal" => 575,
        "ROC" => 576,
        "ROK" => 577,
        "Singapore" => 578,
        "Turkey" => 579,
        "UCT" => 580,
        "US/Alaska" => 581,
        "US/Aleutian" => 582,
        "US/Arizona" => 583,
        "US/Central" => 584,
        "US/East-Indiana" => 585,
        "US/Eastern" => 586,
        "US/Hawaii" => 587,
        "US/Indiana-Starke" => 588,
        "US/Michigan" => 589,
        "US/Mountain" => 590,
        "US/Pacific" => 591,
        "US/Samoa" => 592,
        "UTC" => 593,
        "Universal" => 594,
        "W-SU" => 595,
        "WET" => 596,
        "Zulu" => 597,
        "posixrules" => 598,
    )
    .copied()
}

/// Returns the IANA time zone name assigned to an identifier.
pub(super) fn id_to_name(id: u16) -> Option<&'static str> {
    TZ_NAMES.get(usize::from(id)).copied()
}

/// Returns the number of entries in the table.
pub(super) const fn len() -> usize {
    TZ_NAMES.len()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_and_unique() {
        assert!(TZ_NAMES.windows(2).all(|pair| pair[0] < pair[1]));
    }

    #[test]
    fn every_name_round_trips() {
        for (index, name) in TZ_NAMES.iter().enumerate() {
            let id = name_to_id(name).expect(name);
            assert_eq!(id, index as u16, "{name}");
            assert_eq!(id_to_name(id), Some(*name));
        }
    }

    #[test]
    fn unknown_names_have_no_identifier() {
        for name in ["", "Mars/Olympus_Mons", "Europe/Berlin ", "europe/berlin"] {
            assert_eq!(name_to_id(name), None, "{name}");
        }
    }

    #[test]
    fn utc_id_matches_table() {
        assert_eq!(id_to_name(UTC_ID), Some("UTC"));
    }
}
